services:
  my-mysql:
    image: mysql:8.0
    container_name: my-mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uapp", "-papp"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: yii2-php
    env_file: .env
    environment:
      COOKIE_VALIDATION_KEY: ${COOKIE_VALIDATION_KEY:-dev-fallback-key}
      DB_DSN: ${DB_DSN:-mysql:host=my-mysql;dbname=app}
      DB_USER: ${DB_USER:-app}
      DB_PASS: ${DB_PASS:-app}
    volumes:
      - ./:/var/www/html
    depends_on:
      my-mysql:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: yii2-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: unless-stopped

volumes:
  dbdata:
    name: veterinary_mysql_data
